


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."availability_block_source_type" AS ENUM (
    'direct',
    'airbnb',
    'booking',
    'manual'
);




CREATE TYPE "public"."booking_source_type" AS ENUM (
    'direct',
    'airbnb',
    'booking'
);




CREATE TYPE "public"."booking_status_type" AS ENUM (
    'pending',
    'confirmed',
    'cancelled'
);




CREATE TYPE "public"."civility_type" AS ENUM (
    'mr',
    'mme',
    'not_specified'
);




CREATE TYPE "public"."payment_provider_type" AS ENUM (
    'stripe'
);




CREATE TYPE "public"."payment_status_type" AS ENUM (
    'pending',
    'paid',
    'failed',
    'refunded'
);




CREATE TYPE "public"."promo_type" AS ENUM (
    'percentage_discount',
    'fixed_discount',
    'free_addon'
);



SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."addons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "price" numeric NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "cloudinary_url" "text",
    "cloudinary_public_id" "text"
);




COMMENT ON COLUMN "public"."addons"."cloudinary_url" IS 'URL de l’image affichable directement.';



COMMENT ON COLUMN "public"."addons"."cloudinary_public_id" IS 'Identifiant Cloudinary du fichier';



ALTER TABLE "public"."addons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."addons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."amenities" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "label" "text" NOT NULL,
    "icon_name" "text",
    "description" "text"
);




COMMENT ON TABLE "public"."amenities" IS 'Catalogue global des équipements.';



ALTER TABLE "public"."amenities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."amenities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."availability_blocks" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studio_id" bigint NOT NULL,
    "booking_id" bigint NOT NULL,
    "source" "public"."availability_block_source_type" NOT NULL,
    "start_date" "date" NOT NULL,
    "end_date" "date" NOT NULL,
    "reason" "text"
);




ALTER TABLE "public"."availability_blocks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."availability_blocks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."booking_promotions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "booking_id" bigint NOT NULL,
    "promo_code_id" bigint NOT NULL,
    "discount_amount" numeric,
    "free_addon_id" bigint NOT NULL
);




COMMENT ON TABLE "public"."booking_promotions" IS 'Garder la trace de la promo réellement appliquée à une réservation.';



ALTER TABLE "public"."booking_promotions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."booking_promotions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."bookings" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studio_id" bigint NOT NULL,
    "customer_id" bigint NOT NULL,
    "source" "public"."booking_source_type" NOT NULL,
    "status" "public"."booking_status_type" NOT NULL,
    "check_in" "date" NOT NULL,
    "check_out" "date" NOT NULL,
    "guests_count" bigint NOT NULL,
    "total_price" numeric NOT NULL
);




ALTER TABLE "public"."bookings" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bookings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."customers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "civility" "public"."civility_type",
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text" NOT NULL,
    "phone_country_code" "text" NOT NULL,
    "phone_number" "text" NOT NULL,
    "country_code" "text"
);




ALTER TABLE "public"."customers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."customers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."dashboard_bookings_by_source" AS
 SELECT "source",
    "count"(*) AS "count"
   FROM "public"."bookings"
  GROUP BY "source"
  ORDER BY ("count"(*)) DESC;




CREATE TABLE IF NOT EXISTS "public"."studios" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "slug" "text" NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "capacity" bigint NOT NULL,
    "base_price" numeric DEFAULT '0'::numeric NOT NULL,
    "cleaning_fee" numeric DEFAULT '0'::numeric NOT NULL,
    "currency" "text" DEFAULT 'EUR'::"text" NOT NULL,
    "city" "text",
    "country_code" "text",
    "pets_allowed" boolean DEFAULT false NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "image_cover_public_id" "text",
    "short_description" "text",
    "welcome_title" "text"
);




CREATE OR REPLACE VIEW "public"."dashboard_bookings_by_studio" AS
 SELECT "s"."name" AS "studio",
    "count"("b"."id") AS "count"
   FROM ("public"."bookings" "b"
     JOIN "public"."studios" "s" ON (("s"."id" = "b"."studio_id")))
  GROUP BY "s"."name"
  ORDER BY ("count"("b"."id")) DESC;




CREATE OR REPLACE VIEW "public"."dashboard_bookings_over_time" AS
 SELECT "to_char"("created_at", 'YYYY-MM'::"text") AS "month",
    "count"(*) AS "count"
   FROM "public"."bookings"
  GROUP BY ("to_char"("created_at", 'YYYY-MM'::"text"))
  ORDER BY ("to_char"("created_at", 'YYYY-MM'::"text"));




CREATE OR REPLACE VIEW "public"."dashboard_kpis" AS
 SELECT ( SELECT "count"(*) AS "count"
           FROM "public"."studios") AS "studios_count",
    ( SELECT "count"(*) AS "count"
           FROM "public"."bookings"
          WHERE (("bookings"."check_in" >= CURRENT_DATE) AND ("bookings"."status" = 'confirmed'::"public"."booking_status_type"))) AS "upcoming_bookings",
    ( SELECT "count"(*) AS "count"
           FROM "public"."bookings"
          WHERE ("date_trunc"('month'::"text", "bookings"."created_at") = "date_trunc"('month'::"text", (CURRENT_DATE)::timestamp with time zone))) AS "monthly_bookings",
    ( SELECT COALESCE("sum"("bookings"."total_price"), (0)::numeric) AS "coalesce"
           FROM "public"."bookings"
          WHERE (("bookings"."status" = 'confirmed'::"public"."booking_status_type") AND ("date_trunc"('month'::"text", "bookings"."created_at") = "date_trunc"('month'::"text", (CURRENT_DATE)::timestamp with time zone)))) AS "monthly_revenue";




CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "booking_id" bigint NOT NULL,
    "provider" "public"."payment_provider_type" DEFAULT 'stripe'::"public"."payment_provider_type" NOT NULL,
    "status" "public"."payment_status_type" NOT NULL,
    "amount" numeric,
    "stripe_payment_intent_id" "text" NOT NULL
);




CREATE OR REPLACE VIEW "public"."dashboard_payments_alerts" AS
 SELECT "id" AS "payment_id",
    "booking_id",
    "amount",
    "status"
   FROM "public"."payments" "p"
  WHERE ("status" = ANY (ARRAY['pending'::"public"."payment_status_type", 'failed'::"public"."payment_status_type"]))
  ORDER BY "created_at" DESC;




CREATE OR REPLACE VIEW "public"."dashboard_recent_bookings" AS
 SELECT "b"."id" AS "booking_id",
    "b"."created_at",
    "b"."total_price",
    "s"."name" AS "studio_name"
   FROM ("public"."bookings" "b"
     JOIN "public"."studios" "s" ON (("s"."id" = "b"."studio_id")))
  ORDER BY "b"."created_at" DESC
 LIMIT 10;




CREATE OR REPLACE VIEW "public"."dashboard_revenue_over_time" AS
 SELECT "to_char"("created_at", 'YYYY-MM'::"text") AS "month",
    "sum"("total_price") AS "revenue"
   FROM "public"."bookings"
  WHERE ("status" = 'confirmed'::"public"."booking_status_type")
  GROUP BY ("to_char"("created_at", 'YYYY-MM'::"text"))
  ORDER BY ("to_char"("created_at", 'YYYY-MM'::"text"));




CREATE OR REPLACE VIEW "public"."dashboard_upcoming_arrivals" AS
 SELECT "b"."id" AS "booking_id",
    "b"."check_in",
    "c"."first_name",
    "c"."last_name",
    "s"."name" AS "studio_name"
   FROM (("public"."bookings" "b"
     JOIN "public"."customers" "c" ON (("c"."id" = "b"."customer_id")))
     JOIN "public"."studios" "s" ON (("s"."id" = "b"."studio_id")))
  WHERE (("b"."check_in" >= CURRENT_DATE) AND ("b"."status" = 'confirmed'::"public"."booking_status_type"))
  ORDER BY "b"."check_in"
 LIMIT 10;




CREATE TABLE IF NOT EXISTS "public"."experiences" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "external_url" "text",
    "is_active" boolean DEFAULT true NOT NULL,
    "cover_image_public_id" "text",
    "thumbnail_image_public_id" "text"
);




ALTER TABLE "public"."experiences" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."experiences_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."payments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."payments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."promo_code_addons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "promo_code_id" bigint NOT NULL,
    "addon_id" bigint NOT NULL
);




COMMENT ON TABLE "public"."promo_code_addons" IS 'relier un code promo à un add-on quand la promo est de type :  free_addon';



ALTER TABLE "public"."promo_code_addons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."promo_code_addons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."promo_code_studios" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "promo_code_id" bigint NOT NULL,
    "studio_id" bigint NOT NULL
);




ALTER TABLE "public"."promo_code_studios" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."promo_code_studios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."promo_codes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "code" "text" NOT NULL,
    "name" "text" NOT NULL,
    "promo_type" "public"."promo_type" NOT NULL,
    "percentage_value" numeric,
    "fixed_amount_value" numeric,
    "valid_from" timestamp without time zone,
    "valid_until" timestamp without time zone,
    "max_global_uses" bigint,
    "max_uses_per_customer" bigint,
    "is_active" boolean DEFAULT true NOT NULL
);




ALTER TABLE "public"."promo_codes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."promo_codes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studio_addons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studio_id" bigint NOT NULL,
    "addon_id" bigint NOT NULL
);




ALTER TABLE "public"."studio_addons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studio_addons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studio_amenities" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studio_id" bigint NOT NULL,
    "amenity_id" bigint NOT NULL
);




ALTER TABLE "public"."studio_amenities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studio_amenities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studio_experiences" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studio_id" bigint NOT NULL,
    "experience_id" bigint NOT NULL
);




ALTER TABLE "public"."studio_experiences" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studio_experiences_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."studio_gallery_images" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "studio_id" bigint,
    "image_public_id" "text" NOT NULL,
    "sort_order" bigint DEFAULT '0'::bigint NOT NULL
);




ALTER TABLE "public"."studio_gallery_images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studio_gallery_images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."studios" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."studios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."addons"
    ADD CONSTRAINT "addons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."amenities"
    ADD CONSTRAINT "amenities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."availability_blocks"
    ADD CONSTRAINT "availability_blocks_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."booking_promotions"
    ADD CONSTRAINT "booking_promotions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."customers"
    ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."experiences"
    ADD CONSTRAINT "experiences_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."promo_code_addons"
    ADD CONSTRAINT "promo_code_addons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."promo_code_addons"
    ADD CONSTRAINT "promo_code_addons_unique" UNIQUE ("promo_code_id", "addon_id");



ALTER TABLE ONLY "public"."promo_code_studios"
    ADD CONSTRAINT "promo_code_studios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."promo_code_studios"
    ADD CONSTRAINT "promo_code_studios_unique" UNIQUE ("promo_code_id", "studio_id");



ALTER TABLE ONLY "public"."promo_codes"
    ADD CONSTRAINT "promo_codes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studio_addons"
    ADD CONSTRAINT "studio_addons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studio_addons"
    ADD CONSTRAINT "studio_addons_unique" UNIQUE ("studio_id", "addon_id");



ALTER TABLE ONLY "public"."studio_amenities"
    ADD CONSTRAINT "studio_amenities_unique" UNIQUE ("studio_id", "amenity_id");



ALTER TABLE ONLY "public"."studio_experiences"
    ADD CONSTRAINT "studio_experiences_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studio_experiences"
    ADD CONSTRAINT "studio_experiences_unique" UNIQUE ("studio_id", "experience_id");



ALTER TABLE ONLY "public"."studio_gallery_images"
    ADD CONSTRAINT "studio_gallery_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studios"
    ADD CONSTRAINT "studios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."studios"
    ADD CONSTRAINT "studios_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."availability_blocks"
    ADD CONSTRAINT "availability_blocks_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."availability_blocks"
    ADD CONSTRAINT "availability_blocks_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id");



ALTER TABLE ONLY "public"."booking_promotions"
    ADD CONSTRAINT "booking_promotions_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."booking_promotions"
    ADD CONSTRAINT "booking_promotions_free_addon_id_fkey" FOREIGN KEY ("free_addon_id") REFERENCES "public"."addons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."booking_promotions"
    ADD CONSTRAINT "booking_promotions_promo_code_id_fkey" FOREIGN KEY ("promo_code_id") REFERENCES "public"."promo_codes"("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id");



ALTER TABLE ONLY "public"."bookings"
    ADD CONSTRAINT "bookings_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id");



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "public"."bookings"("id");



ALTER TABLE ONLY "public"."promo_code_addons"
    ADD CONSTRAINT "promo_code_addons_addon_id_fkey" FOREIGN KEY ("addon_id") REFERENCES "public"."addons"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."promo_code_addons"
    ADD CONSTRAINT "promo_code_addons_promo_code_id_fkey" FOREIGN KEY ("promo_code_id") REFERENCES "public"."promo_codes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."promo_code_studios"
    ADD CONSTRAINT "promo_code_studios_promo_code_id_fkey" FOREIGN KEY ("promo_code_id") REFERENCES "public"."promo_codes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."promo_code_studios"
    ADD CONSTRAINT "promo_code_studios_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_addons"
    ADD CONSTRAINT "studio_addons_addon_id_fkey" FOREIGN KEY ("addon_id") REFERENCES "public"."addons"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_addons"
    ADD CONSTRAINT "studio_addons_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_amenities"
    ADD CONSTRAINT "studio_amenities_amenity_id_fkey" FOREIGN KEY ("amenity_id") REFERENCES "public"."amenities"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_amenities"
    ADD CONSTRAINT "studio_amenities_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_experiences"
    ADD CONSTRAINT "studio_experiences_experience_id_fkey" FOREIGN KEY ("experience_id") REFERENCES "public"."experiences"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_experiences"
    ADD CONSTRAINT "studio_experiences_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."studio_gallery_images"
    ADD CONSTRAINT "studio_gallery_images_studio_id_fkey" FOREIGN KEY ("studio_id") REFERENCES "public"."studios"("id") ON DELETE CASCADE;



ALTER TABLE "public"."addons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."amenities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."availability_blocks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."booking_promotions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."bookings" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."customers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."experiences" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."promo_code_addons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."promo_code_studios" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."promo_codes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studio_addons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studio_amenities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studio_experiences" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studio_gallery_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."studios" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";














































































































































































GRANT ALL ON TABLE "public"."addons" TO "postgres";
GRANT ALL ON TABLE "public"."addons" TO "anon";
GRANT ALL ON TABLE "public"."addons" TO "authenticated";
GRANT ALL ON TABLE "public"."addons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."addons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."amenities" TO "postgres";
GRANT ALL ON TABLE "public"."amenities" TO "anon";
GRANT ALL ON TABLE "public"."amenities" TO "authenticated";
GRANT ALL ON TABLE "public"."amenities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."amenities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."availability_blocks" TO "postgres";
GRANT ALL ON TABLE "public"."availability_blocks" TO "anon";
GRANT ALL ON TABLE "public"."availability_blocks" TO "authenticated";
GRANT ALL ON TABLE "public"."availability_blocks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."availability_blocks_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."availability_blocks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."availability_blocks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."availability_blocks_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."booking_promotions" TO "postgres";
GRANT ALL ON TABLE "public"."booking_promotions" TO "anon";
GRANT ALL ON TABLE "public"."booking_promotions" TO "authenticated";
GRANT ALL ON TABLE "public"."booking_promotions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."booking_promotions_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."booking_promotions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."booking_promotions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."booking_promotions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."bookings" TO "postgres";
GRANT ALL ON TABLE "public"."bookings" TO "anon";
GRANT ALL ON TABLE "public"."bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."bookings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."bookings_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."customers" TO "postgres";
GRANT ALL ON TABLE "public"."customers" TO "anon";
GRANT ALL ON TABLE "public"."customers" TO "authenticated";
GRANT ALL ON TABLE "public"."customers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."customers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_bookings_by_source" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_bookings_by_source" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_bookings_by_source" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_bookings_by_source" TO "service_role";



GRANT ALL ON TABLE "public"."studios" TO "postgres";
GRANT ALL ON TABLE "public"."studios" TO "anon";
GRANT ALL ON TABLE "public"."studios" TO "authenticated";
GRANT ALL ON TABLE "public"."studios" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_bookings_by_studio" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_bookings_by_studio" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_bookings_by_studio" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_bookings_by_studio" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_bookings_over_time" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_bookings_over_time" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_bookings_over_time" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_bookings_over_time" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_kpis" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_kpis" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_kpis" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_kpis" TO "service_role";



GRANT ALL ON TABLE "public"."payments" TO "postgres";
GRANT ALL ON TABLE "public"."payments" TO "anon";
GRANT ALL ON TABLE "public"."payments" TO "authenticated";
GRANT ALL ON TABLE "public"."payments" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_payments_alerts" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_payments_alerts" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_payments_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_payments_alerts" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_recent_bookings" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_recent_bookings" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_recent_bookings" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_recent_bookings" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_revenue_over_time" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_revenue_over_time" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_revenue_over_time" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_revenue_over_time" TO "service_role";



GRANT ALL ON TABLE "public"."dashboard_upcoming_arrivals" TO "postgres";
GRANT ALL ON TABLE "public"."dashboard_upcoming_arrivals" TO "anon";
GRANT ALL ON TABLE "public"."dashboard_upcoming_arrivals" TO "authenticated";
GRANT ALL ON TABLE "public"."dashboard_upcoming_arrivals" TO "service_role";



GRANT ALL ON TABLE "public"."experiences" TO "postgres";
GRANT ALL ON TABLE "public"."experiences" TO "anon";
GRANT ALL ON TABLE "public"."experiences" TO "authenticated";
GRANT ALL ON TABLE "public"."experiences" TO "service_role";



GRANT ALL ON SEQUENCE "public"."experiences_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."experiences_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."experiences_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."experiences_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."promo_code_addons" TO "postgres";
GRANT ALL ON TABLE "public"."promo_code_addons" TO "anon";
GRANT ALL ON TABLE "public"."promo_code_addons" TO "authenticated";
GRANT ALL ON TABLE "public"."promo_code_addons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."promo_code_addons_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."promo_code_addons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promo_code_addons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promo_code_addons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."promo_code_studios" TO "postgres";
GRANT ALL ON TABLE "public"."promo_code_studios" TO "anon";
GRANT ALL ON TABLE "public"."promo_code_studios" TO "authenticated";
GRANT ALL ON TABLE "public"."promo_code_studios" TO "service_role";



GRANT ALL ON SEQUENCE "public"."promo_code_studios_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."promo_code_studios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promo_code_studios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promo_code_studios_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."promo_codes" TO "postgres";
GRANT ALL ON TABLE "public"."promo_codes" TO "anon";
GRANT ALL ON TABLE "public"."promo_codes" TO "authenticated";
GRANT ALL ON TABLE "public"."promo_codes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."promo_codes_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."promo_codes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."promo_codes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."promo_codes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studio_addons" TO "postgres";
GRANT ALL ON TABLE "public"."studio_addons" TO "anon";
GRANT ALL ON TABLE "public"."studio_addons" TO "authenticated";
GRANT ALL ON TABLE "public"."studio_addons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studio_addons_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."studio_addons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studio_addons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studio_addons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studio_amenities" TO "postgres";
GRANT ALL ON TABLE "public"."studio_amenities" TO "anon";
GRANT ALL ON TABLE "public"."studio_amenities" TO "authenticated";
GRANT ALL ON TABLE "public"."studio_amenities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studio_amenities_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."studio_amenities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studio_amenities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studio_amenities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studio_experiences" TO "postgres";
GRANT ALL ON TABLE "public"."studio_experiences" TO "anon";
GRANT ALL ON TABLE "public"."studio_experiences" TO "authenticated";
GRANT ALL ON TABLE "public"."studio_experiences" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studio_experiences_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."studio_experiences_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studio_experiences_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studio_experiences_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."studio_gallery_images" TO "postgres";
GRANT ALL ON TABLE "public"."studio_gallery_images" TO "anon";
GRANT ALL ON TABLE "public"."studio_gallery_images" TO "authenticated";
GRANT ALL ON TABLE "public"."studio_gallery_images" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studio_gallery_images_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."studio_gallery_images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studio_gallery_images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studio_gallery_images_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."studios_id_seq" TO "postgres";
GRANT ALL ON SEQUENCE "public"."studios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."studios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."studios_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























